  all_titles:
    vela:
        # The top 30 get unique titles (one per person, unless they are tied)
        1: 424
        2: 425
        3: 426
        4: 427
        5: 428
        6: 429
        7: 430
        8: 431
        9: 432
        10: 433
        11: 434
        12: 435
        13: 436
        14: 437
        15: 438
        16: 439
        17: 440
        18: 441
        19: 442
        20: 443
        21: 444
        22: 445
        23: 446
        24: 447
        25: 448
        26: 449
        27: 450
        28: 451
        29: 452
        30: 453
        # Tiered Ranks (multiple people have the same title, ~20% of active coalition members)
        31: 454
        32: 455
        33: 456
        34: 457
        35: 458
        # Inactive students have this title (people with 0 points, or that have the lowest rank)
        36: 459
    pyxis:
        # Unique titles (one per person)
        1: "Polaris %login (1st)"
        2: "Ursa Major %login (2nd)"
        3: "Ursa Minor %login (3rd)"
        4: "Aries %login (4th)"
        5: "Taurus %login (5th)"
        6: "Gemini %login (6th)"
        7: "Karkinos %login (7th)"
        8: "Leo %login (8th)"
        9: "Virgo %login (9th)"
        10: "Libra %login (10th)"
        11: "Scorpio %login (11th)"
        12: "Sagittarius %login (12th)"
        13: "Capricorn %login (13th)"
        14: "Aquarius %login (14th)"
        15: "Pisces %login (15th)"
        16: "Ophiuchus %login (16th)"
        17: "Corona Australis %login (17th)"
        18: "Corona Borealis %login (18th)"
        19: "Andromeda %login (19th)"
        20: "Centauri %login (20th)"
        21: "Cassiopeia %login (21st)"
        22: "Cygnus %login (22nd)"
        23: "Draco %login (23rd)"
        24: "Hercules %login (24th)"
        25: "Hydra %login (25th)"
        26: "Lupus %login (26th)"
        27: "Lyra %login (27th)"
        28: "Orion %login (28th)"
        29: "Pegasus %login (29th)"
        30: "Serpens %login (30th)"
        # Tiered Ranks (multiple people have the same title, ~20% of active coalition members)
        31: "Aquila %login (A)"
        32: "Boötes %login (B)"
        33: "Corvus %login (C)"
        34: "Delphinus %login (D)"
        35: "Equuleus %login (E)"
        # Inactive students have this title (people with 0 points, or that have the lowest rank)
        36: "Fornax %login (F)"
    cetus:
        # Unique titles (one per person)
        1: "Great Whale %login (1st)"
        2: "Killer Whale %login (2nd)"
        3: "Blue Whale %login (3rd)"
        4: "Right Whale %login (4th)"
        5: "Fin Whale %login (5th)"
        6: "Bowhead Whale %login (6th)"
        7: "Sperm Whale %login (7th)"
        8: "Grey Whale %login (8th)"
        9: "Humpback Whale %login (9th)"
        10: "Bryde's Whale %login (10th)"
        11: "Sei Whale %login (11th)"
        12: "Bottlenose Whale %login (12th)"
        13: "Pilot Whale %login (13th)"
        14: "False Killer Whale %login (14th)"
        15: "Beluga Whale %login (15th)"
        16: "Melon-headed Whale %login (16th)"
        17: "Pygmy Killer Whale %login (17th)"
        18: "Pygmy Right Whale %login (18th)"
        19: "Pygmy Beaked Whale %login (19th)"
        20: "Pygmy Sperm Whale %login (20th)"
        21: "Dwarf Sperm Whale %login (21st)"
        22: "Narwhal %login (22nd)"
        23: "Right Whale Dolphin %login (23rd)"
        24: "Bottlenose Dolphin %login (24th)"
        25: "White-Beaked Dolphin %login (25th)"
        26: "River Dolphin %login (26th)"
        27: "Snubfin Dolphin %login (27th)"
        28: "Hourglass Dolphin %login (28th)"
        29: "Dusky Dolphin %login (29th)"
        30: "Spinner Dolphin %login (30th)"
        # Tiered Ranks (multiple people have the same title, ~20% of active coalition members)
        31: "Common Dolphin %login (A)"
        32: "Porpoise %login (B)"
        33: "Manatee %login (C)"
        34: "Guppy %login (D)"
        35: "Krill %login (E)"
        # Inactive students have this title (people with 0 points, or that have the lowest rank)
        36: "Beached Whale %login (F)"
