  all_titles:
    vela:
        v1: "Captain %login (1st)"
        v2: "Commodore %login (2nd)"
        v3: "Commander %login (3rd)"
        v4: "Lieutenant %login (4th)"
        v5: "Warrant Officer %login (5th)"
        v6: "Master %login (6th)"
        v7: "First Mate %login (7th)"
        v8: "Second Mate %login (8th)"
        v9: "Third Mate %login (9th)"
        v10: "Midshipman %login (10th)"
        v11: "Chief Steward %login (11th)"
        v12: "Boatswain %login (12th)"
        v13: "Shipwright %login (13th)"
        v14: "Quartermaster %login (14th)"
        v15: "Helmsman %login (15th)"
        v16: "Skipper %login (16th)"
        v17: "Ship's Corporal %login (17th)"
        v18: "Watch Captain %login (18th)"
        v19: "Privateer %login (19th)"
        v20: "Mariner %login (20th)"
        v21: "Sailmaker %login (21st)"
        v22: "Caulker %login (22nd)"
        v23: "Ropemaker %login (23rd)"
        v24: "Captain's Clerk %login (24th)"
        v25: "Master's Mate %login (25th)"
        v26: "Midshipman's Mate %login (26th)"
        v27: "Boatswain's Mate %login (27th)"
        v28: "Quartermaster's Mate %login (28th)"
        v29: "Sailmaker's Mate %login (29th)"
        v30: "Caulker's Mate %login (30th)"
        vA: "Leading Hand %login (A)"
        vB: "Able Seaman %login (B)"
        vC: "Ordinary Seaman %login (C)"
        vD: "Swabby %login (D)"
        vE: "Powder Monkey %login (E)"
        vF: "Landlubber %login (F)"
    pyxis:
        v1: "Polaris %login (1st)"
        v2: "Ursa Major %login (2nd)"
        v3: "Ursa Minor %login (3rd)"
        v4: "Aries %login (4th)"
        v5: "Taurus %login (5th)"
        v6: "Gemini %login (6th)"
        v7: "Karkinos %login (7th)"
        v8: "Leo %login (8th)"
        v9: "Virgo %login (9th)"
        v10: "Libra %login (10th)"
        v11: "Scorpio %login (11th)"
        v12: "Sagittarius %login (12th)"
        v13: "Capricorn %login (13th)"
        v14: "Aquarius %login (14th)"
        v15: "Pisces %login (15th)"
        v16: "Ophiuchus %login (16th)"
        v17: "Corona Australis %login (17th)"
        v18: "Corona Borealis %login (18th)"
        v19: "Andromeda %login (19th)"
        v20: "Centauri %login (20th)"
        v21: "Cassiopeia %login (21st)"
        v22: "Cygnus %login (22nd)"
        v23: "Draco %login (23rd)"
        v24: "Hercules %login (24th)"
        v25: "Hydra %login (25th)"
        v26: "Lupus %login (26th)"
        v27: "Lyra %login (27th)"
        v28: "Orion %login (28th)"
        v29: "Pegasus %login (29th)"
        v30: "Serpens %login (30th)"
        vA: "Aquila %login (A)"
        vB: "Boötes %login (B)"
        vC: "Corvus %login (C)"
        vD: "Delphinus %login (D)"
        vE: "Equuleus %login (E)"
        vF: "Fornax %login (F)"
    cetus:
        v1: "Great Whale %login (1st)"
        v2: "Killer Whale %login (2nd)"
        v3: "Blue Whale %login (3rd)"
        v4: "Right Whale %login (4th)"
        v5: "Fin Whale %login (5th)"
        v6: "Bowhead Whale %login (6th)"
        v7: "Sperm Whale %login (7th)"
        v8: "Grey Whale %login (8th)"
        v9: "Humpback Whale %login (9th)"
        v10: "Bryde's Whale %login (10th)"
        v11: "Sei Whale %login (11th)"
        v12: "Bottlenose Whale %login (12th)"
        v13: "Pilot Whale %login (13th)"
        v14: "False Killer Whale %login (14th)"
        v15: "Beluga Whale %login (15th)"
        v16: "Melon-headed Whale %login (16th)"
        v17: "Pygmy Killer Whale %login (17th)"
        v18: "Pygmy Right Whale %login (18th)"
        v19: "Pygmy Beaked Whale %login (19th)"
        v20: "Pygmy Sperm Whale %login (20th)"
        v21: "Dwarf Sperm Whale %login (21st)"
        v22: "Narwhal %login (22nd)"
        v23: "Right Whale Dolphin %login (23rd)"
        v24: "Bottlenose Dolphin %login (24th)"
        v25: "White-Beaked Dolphin %login (25th)"
        v26: "River Dolphin %login (26th)"
        v27: "Snubfin Dolphin %login (27th)"
        v28: "Hourglass Dolphin %login (28th)"
        v29: "Dusky Dolphin %login (29th)"
        v30: "Spinner Dolphin %login (30th)"
        vA: "Common Dolphin %login (A)"
        vB: "Porpoise %login (B)"
        vC: "Manatee %login (C)"
        vD: "Guppy %login (D)"
        vE: "Krill %login (E)"
        vF: "Beached Whale %login (F)"
